import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import AppSidebarClient from "@/components/AppSidebarClient";
import AllProviders from "@/components/allProviders";
import { Toaster } from "@/components/ui/toast";
import MobileNavigation from "@/components/mobile_nav";
import CommentBox from "@/components/comments";

// Налаштовуємо шрифт Inter
const inter = Inter({
  subsets: ["latin", "cyrillic"], // додаємо кирилицю, якщо потрібна українська
  variable: "--font-inter", // створюємо CSS-змінну
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ua">
      <body className={`${inter.variable} font-sans antialiased flex`}>
        <AllProviders>
          <AppSidebarClient />
          <Toaster />
          <div className="wrapper">
            <Header />
            <div className="page">{children}</div>
            {/* <CommentBox /> */}
            <MobileNavigation />
          </div>
     
        </AllProviders>
      </body>
    </html>
  );
}
